export const ActionTypes = {
    USER_ACTIONS: {
        SET_CURRENT_USER: 'SET_CURRENT_USER'
    },
    CART_ACTIONS: {
        TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
        ADD_ITEMS: 'ADD_ITEMS',
        CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
        REMOVE_ITEM: 'REMOVE_ITEM'
    },
    SHOP_ACTIONS:{
        FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
        FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
        FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTION_FAILURE'
    }
}

export default ActionTypes;